import { CustomizeIconType } from 'oh-vue-icons';
import {
  BiGithub,
  CoLinkedinIn,
  MdEmailOutlined,
  FaChevronRight,
  BiChevronUp,
  CoHamburgerMenu,
  HiDatabase,
  MdLaptopmac,
  HiAcademicCap,
  BiFiletypeHtml,
  PrTimes,
  BiFiletypePdf,
  ViFileTypeTypescriptOfficial,
  ViFileTypeTailwind,
  ViFileTypeReactjs,
  ViFileTypeNode,
  ViFileTypeVue,
  RiEnglishInput,
  BiGlobe2,
  RiEye2Line,
  OiRepoPush,
  IoGitPullRequestSharp,
  IoGitBranch,
  FaSpinner,
  HiLightBulb,
  HiSolidLightBulb,
} from 'oh-vue-icons/icons';

export const iconsToAdd: CustomizeIconType[] = [
  BiGithub,
  CoLinkedinIn,
  MdEmailOutlined,
  FaChevronRight,
  CoHamburgerMenu,
  HiDatabase,
  BiChevronUp,
  MdLaptopmac,
  HiAcademicCap,
  BiFiletypeHtml,
  PrTimes,
  BiFiletypePdf,
  ViFileTypeTypescriptOfficial,
  ViFileTypeTailwind,
  ViFileTypeReactjs,
  ViFileTypeNode,
  ViFileTypeVue,
  RiEnglishInput,
  BiGlobe2,
  RiEye2Line,
  OiRepoPush,
  IoGitPullRequestSharp,
  IoGitBranch,
  FaSpinner,
  HiLightBulb,
  HiSolidLightBulb,
];