name: Preview Deployment workflow
env:
 VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
 VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
 VITE_I18N_FALLBACK_LOCALE: ${{ secrets.VITE_I18N_FALLBACK_LOCALE }}
 VITE_I18N_LOCALE: ${{ secrets.VITE_I18N_LOCALE }}
 VITE_I18N_SUPPORTED_LOCALE: ${{ secrets.VITE_I18N_SUPPORTED_LOCALE }}
 VITE_GITHUB_SOURCE: ${{ secrets.VITE_GITHUB_SOURCE }}
 VITE_GITHUB_USER: ${{ secrets.VITE_GITHUB_USER }}

on:
 push:
  branches-ignore:
   - main

jobs:
 build-preview:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [18.16.0]

  steps:
   - uses: actions/checkout@v4
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version }}
      cache: 'yarn'
   - name: Install packages
     run: yarn install --frozen-lockfile
   - name: Run tests locally
     run: yarn test:coverage
   - name: Install Vercel CLI
     run: yarn global add vercel@latest
   - name: Pull Vercel Environment Information
     run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
   - name: Build Project Artifacts
     run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
   - name: Deploy Project Artifacts to Vercel
     run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}